-- See below DDL of project's tables :

create table person
(
    id integer generated by default as identity primary key,
    name varchar not null unique,
    year_of_birth integer constraint person_year_of_birth_check check (year_of_birth > 1923),
    whom_created_by varchar(20)
);

create table videocassette
(
    id integer generated by default as identity primary key,
    title varchar not null unique,
    director varchar not null,
    year_of_production integer constraint videocassette_year_of_production_check
        check (year_of_production >= 1888),
    person_id integer references person(id) on delete set null
);

create table app_user
(
    id integer generated by default as identity primary key,
    username varchar(15) not null,
    password varchar not null,
    role varchar(100) not null
);